#ifndef TP_WORMS_CONSTANTS_H
#define TP_WORMS_CONSTANTS_H

// DIMENS
const float WORM_SIZE = 1.2f;
const float CLIENT_FPS = 25.0f;

const float BEAMS_HEIGHT = 0.8f;
const float LARGE_BEAM_WIDTH = 6.0f;
const float LARGE_BEAM_HEIGHT = BEAMS_HEIGHT;
const float SHORT_BEAM_WIDTH = 3.0f;
const float SHORT_BEAM_HEIGHT = BEAMS_HEIGHT;
const float MAX_BEAM_WALKABLE_ANGLE = 45.0f;

const float INITIAL_PROJECTILE_IMPULSE = 20;
const float INITIAL_PROJECTILE_IMPULSE_X = INITIAL_PROJECTILE_IMPULSE;
const float INITIAL_PROJECTILE_IMPULSE_y = INITIAL_PROJECTILE_IMPULSE;
const float PROJECTILE_DENSITY = 1;
const float SHOOT_POTENCY = 10;

#endif
